// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsZLMAh8sAqeJMSdSM5tCQdMpevkAhZSw',
    appId: '1:93084755412:web:90bbfdb907121303aa2241',
    messagingSenderId: '93084755412',
    projectId: 'site-720',
    authDomain: 'site-720.firebaseapp.com',
    storageBucket: 'site-720.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyOkHGKk2ts8k-FcVrd2e1OtKXl-ePF9k',
    appId: '1:93084755412:android:4e440c022ff2a466aa2241',
    messagingSenderId: '93084755412',
    projectId: 'site-720',
    storageBucket: 'site-720.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyyxQb9aURn6As6DodTqiSjIrzwNzPy0Y',
    appId: '1:93084755412:ios:1d0e125534a8d6d6aa2241',
    messagingSenderId: '93084755412',
    projectId: 'site-720',
    storageBucket: 'site-720.firebasestorage.app',
    iosBundleId: 'com.example.site720Client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyyxQb9aURn6As6DodTqiSjIrzwNzPy0Y',
    appId: '1:93084755412:ios:1d0e125534a8d6d6aa2241',
    messagingSenderId: '93084755412',
    projectId: 'site-720',
    storageBucket: 'site-720.firebasestorage.app',
    iosBundleId: 'com.example.site720Client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsZLMAh8sAqeJMSdSM5tCQdMpevkAhZSw',
    appId: '1:93084755412:web:6d9b2e93b8c7bdb6aa2241',
    messagingSenderId: '93084755412',
    projectId: 'site-720',
    authDomain: 'site-720.firebaseapp.com',
    storageBucket: 'site-720.firebasestorage.app',
  );
}
