// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc-TCQUfAvRLWkdrTQ1UKicJzgOoggOho',
    appId: '1:249155218155:web:8736e1fc433b57a6a96cae',
    messagingSenderId: '249155218155',
    projectId: 'site720-client',
    authDomain: 'site720-client.firebaseapp.com',
    storageBucket: 'site720-client.firebasestorage.app',
    measurementId: 'G-LTMCD7G175',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkyTaK103WrTEE61cuV-c7CwU7R09_U54',
    appId: '1:249155218155:android:8e11b3a8d35e882da96cae',
    messagingSenderId: '249155218155',
    projectId: 'site720-client',
    storageBucket: 'site720-client.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlP0dcuk1ZyHEVv0L2vropZs_EG5q8l1A',
    appId: '1:249155218155:ios:7039ee71e56275bda96cae',
    messagingSenderId: '249155218155',
    projectId: 'site720-client',
    storageBucket: 'site720-client.firebasestorage.app',
    iosBundleId: 'com.home4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlP0dcuk1ZyHEVv0L2vropZs_EG5q8l1A',
    appId: '1:249155218155:ios:7039ee71e56275bda96cae',
    messagingSenderId: '249155218155',
    projectId: 'site720-client',
    storageBucket: 'site720-client.firebasestorage.app',
    iosBundleId: 'com.home4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc-TCQUfAvRLWkdrTQ1UKicJzgOoggOho',
    appId: '1:249155218155:web:fd4eb6164ee5f52ea96cae',
    messagingSenderId: '249155218155',
    projectId: 'site720-client',
    authDomain: 'site720-client.firebaseapp.com',
    storageBucket: 'site720-client.firebasestorage.app',
    measurementId: 'G-PJ8YNT4ZGW',
  );
}
